name: Test Android Manifest

on:
  workflow_dispatch:
    inputs:
      manifest_url:
        description: 'URL untuk Android manifest'
        required: true
        default: 'https://github.com/ScandiumOS/android_scandium_manifest.git'
      branch:
        description: 'Branch yang ingin diuji'
        required: true
        default: 'Holocaust_A13'

jobs:
  test-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create bin Directory and Download Repo
        run: |
          mkdir ~/bin
          echo "PATH=~/bin:$PATH" >> $GITHUB_ENV
          cd ~/bin
          curl -O http://commondatastorage.googleapis.com/git-repo-downloads/repo
          chmod a+x ~/bin/repo

      - name: Initialize Repo
        id: init_repo
        run: |
          echo "Menginisialisasi repo dengan URL: ${{ github.event.inputs.manifest_url }} dan branch: ${{ github.event.inputs.branch }}"
          repo init -u --depth=1 ${{ github.event.inputs.manifest_url }} -b ${{ github.event.inputs.branch }} || echo "Error: Gagal menginisialisasi repo."

      - name: Sync Repo
        id: sync_repo
        run: |
          echo "Menjalankan repo sync..."
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
